"""Contracts for standalone Phase D compare reporting."""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from llm_sched.contracts.sweep_report import (
    SweepBandwidthPressureCompareSummary,
    SweepFittedLayerDelta,
    SweepIssue,
    SweepNodeDelta,
    SweepScalarDelta,
    SweepVMEMPressureCompareSummary,
)


def _zero_scalar_delta() -> SweepScalarDelta:
    return SweepScalarDelta(
        baseline_value=0.0,
        candidate_value=0.0,
        delta_value=0.0,
        delta_ratio=0.0,
    )


class PhaseDCompareVerdictSummary(BaseModel):
    model_config = ConfigDict(extra="forbid")

    verdict: Literal["candidate-better", "baseline-better", "mixed", "neutral"] = "neutral"
    preferred_target_profile_name: str = ""
    primary_metric: str = ""
    primary_metric_delta: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    primary_phase: str = ""
    dominant_layer_id: int | None = None
    dominant_node_id: str | None = None


class PhaseDCompareModeSummary(BaseModel):
    model_config = ConfigDict(extra="forbid")

    compare_count: int = Field(ge=0, default=0)
    candidate_better_count: int = Field(ge=0, default=0)
    baseline_better_count: int = Field(ge=0, default=0)
    mixed_count: int = Field(ge=0, default=0)
    neutral_count: int = Field(ge=0, default=0)


class PhaseDPrefillCompareRow(BaseModel):
    model_config = ConfigDict(extra="forbid")

    scenario_name: str
    baseline_target_profile_name: str
    candidate_target_profile_name: str
    baseline_schedule_kind: Literal["single-core", "dual-core"]
    candidate_schedule_kind: Literal["single-core", "dual-core"]
    profile_diff_fields: list[str] = Field(default_factory=list)
    layer_delta_count: int = Field(ge=0)
    verdict_summary: PhaseDCompareVerdictSummary = Field(default_factory=PhaseDCompareVerdictSummary)
    node_delta_count: int = Field(ge=0, default=0)
    fitted_layer_delta_count: int = Field(ge=0, default=0)
    node_deltas: list[SweepNodeDelta] = Field(default_factory=list)
    fitted_layer_deltas: list[SweepFittedLayerDelta] = Field(default_factory=list)
    bandwidth_pressure_compare: SweepBandwidthPressureCompareSummary | None = None
    vmem_pressure_compare: SweepVMEMPressureCompareSummary | None = None
    estimated_cycles: SweepScalarDelta
    critical_path_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    tokens_per_cycle: SweepScalarDelta
    tokens_per_fitted_work_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    tokens_per_critical_path_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    cycles_per_token: SweepScalarDelta
    fitted_cycles_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    bytes_per_cycle: SweepScalarDelta
    max_region_utilization: SweepScalarDelta


class PhaseDDecodeCompareRow(BaseModel):
    model_config = ConfigDict(extra="forbid")

    scenario_name: str
    baseline_target_profile_name: str
    candidate_target_profile_name: str
    baseline_schedule_kind: Literal["single-core", "dual-core"]
    candidate_schedule_kind: Literal["single-core", "dual-core"]
    profile_diff_fields: list[str] = Field(default_factory=list)
    layer_delta_count: int = Field(ge=0)
    verdict_summary: PhaseDCompareVerdictSummary = Field(default_factory=PhaseDCompareVerdictSummary)
    node_delta_count: int = Field(ge=0, default=0)
    fitted_layer_delta_count: int = Field(ge=0, default=0)
    node_deltas: list[SweepNodeDelta] = Field(default_factory=list)
    fitted_layer_deltas: list[SweepFittedLayerDelta] = Field(default_factory=list)
    bandwidth_pressure_compare: SweepBandwidthPressureCompareSummary | None = None
    vmem_pressure_compare: SweepVMEMPressureCompareSummary | None = None
    estimated_cycles: SweepScalarDelta
    critical_path_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    projection_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_io_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    attention_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    cycles_per_token: SweepScalarDelta
    fitted_work_cycles_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    critical_path_cycles_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_related_cycle_share: SweepScalarDelta
    kv_related_fitted_work_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    kv_related_bytes: SweepScalarDelta
    sync_cycles: SweepScalarDelta
    sync_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    sync_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_fitted_work_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_bytes: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_byte_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_bytes_per_cycle: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_cycle_share: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_vmem: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr_backed_staged: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_ddr_persistent: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_vmem_local: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_activation: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_weight: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_read_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_write_bytes_kv_cache: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_compute_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_memory_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_sync_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_compression_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_compression_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_schedule_overhang_cycles: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slots_per_token: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slot_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_occupied_slot_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_span_imbalance_slots: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)
    other_span_balance_ratio: SweepScalarDelta = Field(default_factory=_zero_scalar_delta)


class PhaseDCompareReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    report_name: str
    source_sweep_name: str
    baseline_target_profile_name: str
    completed_run_count: int = Field(ge=0)
    failed_run_count: int = Field(ge=0)
    comparison_count: int = Field(ge=0)
    prefill_compare_count: int = Field(ge=0)
    decode_compare_count: int = Field(ge=0)
    prefill_summary: PhaseDCompareModeSummary = Field(default_factory=PhaseDCompareModeSummary)
    decode_summary: PhaseDCompareModeSummary = Field(default_factory=PhaseDCompareModeSummary)
    prefill_compares: list[PhaseDPrefillCompareRow] = Field(default_factory=list)
    decode_compares: list[PhaseDDecodeCompareRow] = Field(default_factory=list)
    issues: list[SweepIssue] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_counts(self) -> "PhaseDCompareReport":
        if self.prefill_compare_count != len(self.prefill_compares):
            raise ValueError("prefill_compare_count must match len(prefill_compares)")
        if self.decode_compare_count != len(self.decode_compares):
            raise ValueError("decode_compare_count must match len(decode_compares)")
        if self.comparison_count != self.prefill_compare_count + self.decode_compare_count:
            raise ValueError("comparison_count must match prefill_compare_count + decode_compare_count")
        return self
